import { BusinessType, BusinessModuleConfig, CatalogItemType } from '../types';

export interface BusinessTypeMeta {
  id: BusinessType;
  label: string;
  categoryName: string; // e.g. "Menu Category" vs "Department"
  itemLabel: string; // e.g. "Menu Item", "Service", "Product", "Room"
  itemPlural: string;
  defaultItemType: CatalogItemType;
  supportedItemTypes: CatalogItemType[];
  description: string;
  iconName: string; // lucide icon name
  defaultModules: BusinessModuleConfig;
  suggestedCategories: string[];
}

export const BUSINESS_TYPES: Record<BusinessType, BusinessTypeMeta> = {
  retail: {
    id: 'retail',
    label: 'Retail & General Shop',
    categoryName: 'Category',
    itemLabel: 'Product',
    itemPlural: 'Products',
    defaultItemType: 'product',
    supportedItemTypes: ['product', 'package', 'custom'],
    description: 'Sell physical goods with categories, variants, inventory and WhatsApp checkout.',
    iconName: 'ShoppingBag',
    defaultModules: {
      products: true,
      services: false,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: true,
      booking_appointments: false,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: true,
    },
    suggestedCategories: ['Featured', 'Best Sellers', 'New Arrivals', 'Special Offers'],
  },
  restaurant: {
    id: 'restaurant',
    label: 'Restaurant, Cafe & Food',
    categoryName: 'Menu Section',
    itemLabel: 'Menu Item',
    itemPlural: 'Menu Items',
    defaultItemType: 'menu_item',
    supportedItemTypes: ['menu_item', 'package', 'custom'],
    description: 'Digital food menu with add-ons, spice levels, prep time, dine-in & takeaway delivery.',
    iconName: 'UtensilsCrossed',
    defaultModules: {
      products: false,
      services: false,
      menu: true,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: true,
      booking_appointments: false,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: false,
    },
    suggestedCategories: ['Starters & Appetizers', 'Main Course', 'Biryani & Rice', 'Beverages & Mocktails', 'Desserts'],
  },
  grocery: {
    id: 'grocery',
    label: 'Grocery & Supermarket',
    categoryName: 'Aisle / Category',
    itemLabel: 'Grocery Item',
    itemPlural: 'Grocery Items',
    defaultItemType: 'product',
    supportedItemTypes: ['product', 'package'],
    description: 'Quick local grocery ordering, fast unit pricing (kg, g, pack) & daily delivery.',
    iconName: 'Store',
    defaultModules: {
      products: true,
      services: false,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: true,
      booking_appointments: false,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: true,
    },
    suggestedCategories: ['Fresh Vegetables', 'Dairy & Eggs', 'Grains & Pulses', 'Snacks & Beverages', 'Household Essentials'],
  },
  bakery: {
    id: 'bakery',
    label: 'Bakery & Sweets',
    categoryName: 'Bakery Category',
    itemLabel: 'Bakery Item',
    itemPlural: 'Bakery Items',
    defaultItemType: 'product',
    supportedItemTypes: ['product', 'custom'],
    description: 'Cakes, pastries, customized sweets with weight variants and advance booking.',
    iconName: 'Cake',
    defaultModules: {
      products: true,
      services: false,
      menu: true,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: true,
      booking_appointments: false,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: false,
    },
    suggestedCategories: ['Custom Cakes', 'Pastries & Desserts', 'Artisanal Breads', 'Traditional Sweets', 'Cookies & Savouries'],
  },
  salon: {
    id: 'salon',
    label: 'Salon, Spa & Beauty',
    categoryName: 'Service Category',
    itemLabel: 'Beauty Service',
    itemPlural: 'Services',
    defaultItemType: 'service',
    supportedItemTypes: ['service', 'product', 'package'],
    description: 'Hair, skin, spa services with duration times, pricing and slot booking.',
    iconName: 'Scissors',
    defaultModules: {
      products: true,
      services: true,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: false,
      booking_appointments: true,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: false,
    },
    suggestedCategories: ['Hair Styling & Cut', 'Skin & Facials', 'Spa & Massage', 'Bridal Packages', 'Grooming Products'],
  },
  clinic: {
    id: 'clinic',
    label: 'Clinic & Healthcare',
    categoryName: 'Department',
    itemLabel: 'Consultation / Service',
    itemPlural: 'Services',
    defaultItemType: 'service',
    supportedItemTypes: ['service', 'product'],
    description: 'Doctor appointments, consultations, health checkups and clinic services.',
    iconName: 'Stethoscope',
    defaultModules: {
      products: false,
      services: true,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: false,
      table_delivery: false,
      booking_appointments: true,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: false,
      digital_card: true,
      inventory_tracking: false,
    },
    suggestedCategories: ['General Consultation', 'Specialist Care', 'Diagnostic Packages', 'Follow-up Sessions'],
  },
  hotel: {
    id: 'hotel',
    label: 'Hotel, Resort & Stays',
    categoryName: 'Room Type',
    itemLabel: 'Room / Villa',
    itemPlural: 'Rooms & Stays',
    defaultItemType: 'room',
    supportedItemTypes: ['room', 'service', 'package'],
    description: 'Rooms, suites, villas with check-in/out dates, guest capacity, amenities and bookings.',
    iconName: 'BedDouble',
    defaultModules: {
      products: false,
      services: true,
      menu: false,
      rooms: true,
      vehicles: false,
      cart_ordering: false,
      table_delivery: false,
      booking_appointments: false,
      stay_booking: true,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: false,
    },
    suggestedCategories: ['Deluxe Rooms', 'Executive Suites', 'Family Villas', 'Day Pass & Packages'],
  },
  rental: {
    id: 'rental',
    label: 'Car & Vehicle Rental',
    categoryName: 'Vehicle Fleet',
    itemLabel: 'Vehicle',
    itemPlural: 'Vehicles',
    defaultItemType: 'vehicle',
    supportedItemTypes: ['vehicle', 'service'],
    description: 'Self-drive cars, luxury bikes, vans with transmission/fuel specs & rental booking.',
    iconName: 'Car',
    defaultModules: {
      products: false,
      services: true,
      menu: false,
      rooms: false,
      vehicles: true,
      cart_ordering: false,
      table_delivery: false,
      booking_appointments: false,
      stay_booking: false,
      rental_booking: true,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: false,
    },
    suggestedCategories: ['SUVs & 7-Seaters', 'Sedans & Hatchbacks', 'Luxury Cars', 'Bikes & Scooters'],
  },
  real_estate: {
    id: 'real_estate',
    label: 'Real Estate & Property',
    categoryName: 'Property Type',
    itemLabel: 'Property Listing',
    itemPlural: 'Properties',
    defaultItemType: 'property',
    supportedItemTypes: ['property', 'service'],
    description: 'Apartments, plots, commercial spaces with photos, specs and direct WhatsApp inquiries.',
    iconName: 'Building2',
    defaultModules: {
      products: false,
      services: true,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: false,
      table_delivery: false,
      booking_appointments: true,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: false,
      digital_card: true,
      inventory_tracking: false,
    },
    suggestedCategories: ['Residential Apartments', 'Luxury Villas', 'Commercial Spaces', 'Plots & Lands'],
  },
  fashion: {
    id: 'fashion',
    label: 'Fashion & Boutique',
    categoryName: 'Collection',
    itemLabel: 'Apparel Item',
    itemPlural: 'Apparel',
    defaultItemType: 'product',
    supportedItemTypes: ['product', 'custom'],
    description: 'Designer clothing, ethnic wear, footwear with size/color variants and cart checkout.',
    iconName: 'Shirt',
    defaultModules: {
      products: true,
      services: false,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: true,
      booking_appointments: false,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: true,
    },
    suggestedCategories: ["Men's Wear", "Women's Ethnic", "Western Wear", "Footwear & Bags", "Festive Collection"],
  },
  jewellery: {
    id: 'jewellery',
    label: 'Jewellery & Ornaments',
    categoryName: 'Collection',
    itemLabel: 'Jewellery Piece',
    itemPlural: 'Jewellery',
    defaultItemType: 'product',
    supportedItemTypes: ['product', 'custom'],
    description: 'Gold, diamond, silver, artificial jewellery showcase with high-res photo gallery.',
    iconName: 'Gem',
    defaultModules: {
      products: true,
      services: false,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: true,
      booking_appointments: true,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: true,
    },
    suggestedCategories: ['Necklace Sets', 'Earrings & Jhumkas', 'Rings & Bangles', 'Bridal Collection'],
  },
  electronics: {
    id: 'electronics',
    label: 'Electronics & Mobiles',
    categoryName: 'Gadget Category',
    itemLabel: 'Electronic Item',
    itemPlural: 'Gadgets',
    defaultItemType: 'product',
    supportedItemTypes: ['product', 'service'],
    description: 'Smartphones, accessories, home appliances, repair services and warranty details.',
    iconName: 'Smartphone',
    defaultModules: {
      products: true,
      services: true,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: true,
      booking_appointments: true,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: true,
    },
    suggestedCategories: ['Smartphones & Tablets', 'Audio & Headphones', 'Smart Watches', 'Accessories & Cables'],
  },
  furniture: {
    id: 'furniture',
    label: 'Furniture & Home Decor',
    categoryName: 'Room / Furniture Category',
    itemLabel: 'Furniture Piece',
    itemPlural: 'Furniture Items',
    defaultItemType: 'product',
    supportedItemTypes: ['product', 'custom'],
    description: 'Sofas, beds, dining sets, lighting and interior products with custom inquiries.',
    iconName: 'Armchair',
    defaultModules: {
      products: true,
      services: true,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: true,
      booking_appointments: true,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: true,
    },
    suggestedCategories: ['Living Room Sofas', 'Bedroom Sets', 'Dining & Kitchen', 'Home Decor & Lamps'],
  },
  education: {
    id: 'education',
    label: 'Tutor, Coaching & Courses',
    categoryName: 'Subject / Course Category',
    itemLabel: 'Course / Batch',
    itemPlural: 'Courses & Batches',
    defaultItemType: 'course',
    supportedItemTypes: ['course', 'service', 'product'],
    description: 'Classes, coaching batches, test series, study materials and enrollment inquiries.',
    iconName: 'GraduationCap',
    defaultModules: {
      products: true,
      services: true,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: false,
      booking_appointments: true,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: false,
    },
    suggestedCategories: ['Class 10-12 Batches', 'Competitive Exam Prep', 'Spoken English & Skills', 'Study Materials'],
  },
  services: {
    id: 'services',
    label: 'Professional & Home Services',
    categoryName: 'Service Category',
    itemLabel: 'Service',
    itemPlural: 'Services',
    defaultItemType: 'service',
    supportedItemTypes: ['service', 'package', 'product'],
    description: 'Electrician, plumber, cleaning, AC repair, legal, accounting and doorstep services.',
    iconName: 'Wrench',
    defaultModules: {
      products: true,
      services: true,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: false,
      booking_appointments: true,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: false,
    },
    suggestedCategories: ['AC Repair & Service', 'Plumbing & Sanitary', 'Electrical & Wiring', 'Deep Cleaning'],
  },
  agency: {
    id: 'agency',
    label: 'Digital Agency & Freelancer',
    categoryName: 'Service Package',
    itemLabel: 'Service Package',
    itemPlural: 'Packages',
    defaultItemType: 'package',
    supportedItemTypes: ['package', 'service'],
    description: 'Web development, graphic design, social media marketing and custom quotes.',
    iconName: 'Laptop',
    defaultModules: {
      products: false,
      services: true,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: false,
      table_delivery: false,
      booking_appointments: true,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: false,
    },
    suggestedCategories: ['Website Development', 'Brand & Logo Design', 'Social Media Management', 'SEO & Ads Growth'],
  },
  custom: {
    id: 'custom',
    label: 'Other / Custom Business',
    categoryName: 'Category',
    itemLabel: 'Item',
    itemPlural: 'Items',
    defaultItemType: 'product',
    supportedItemTypes: ['product', 'service', 'custom'],
    description: 'Tailor-made setup for unique products, specialized services and hybrid businesses.',
    iconName: 'Briefcase',
    defaultModules: {
      products: true,
      services: true,
      menu: false,
      rooms: false,
      vehicles: false,
      cart_ordering: true,
      table_delivery: true,
      booking_appointments: true,
      stay_booking: false,
      rental_booking: false,
      inquiries: true,
      reviews: true,
      offers: true,
      digital_card: true,
      inventory_tracking: true,
    },
    suggestedCategories: ['Featured Offerings', 'Popular Choices', 'Custom Orders'],
  },
};

export const MODULE_DEFINITIONS: {
  key: keyof BusinessModuleConfig;
  label: string;
  description: string;
  iconName: string;
  recommendedFor: string;
}[] = [
  {
    key: 'products',
    label: 'Physical Products',
    description: 'Catalog with inventory, SKUs, and variant pricing.',
    iconName: 'Package',
    recommendedFor: 'Retail, Grocery, Fashion, Electronics',
  },
  {
    key: 'menu',
    label: 'Food Menu & Add-ons',
    description: 'Restaurant-style menu with food tags (Veg/Non-veg), toppings, and prep time.',
    iconName: 'UtensilsCrossed',
    recommendedFor: 'Restaurants, Cafes, Bakeries, Food Stalls',
  },
  {
    key: 'services',
    label: 'Service Offerings',
    description: 'Services with duration, pricing, and consultation details.',
    iconName: 'Sparkles',
    recommendedFor: 'Salons, Spas, Clinics, Home Services, Freelancers',
  },
  {
    key: 'rooms',
    label: 'Rooms & Stays',
    description: 'Hotel room types, bed configurations, guest capacity, and amenities.',
    iconName: 'BedDouble',
    recommendedFor: 'Hotels, Resorts, Homestays, Guest Houses',
  },
  {
    key: 'vehicles',
    label: 'Vehicle Fleet',
    description: 'Cars, bikes, and rentals with specs, fuel type, transmission, and daily rates.',
    iconName: 'Car',
    recommendedFor: 'Car & Bike Rentals, Transport Services',
  },
  {
    key: 'cart_ordering',
    label: 'Shopping Cart & Orders',
    description: 'Allow customers to add items to cart and place orders instantly.',
    iconName: 'ShoppingCart',
    recommendedFor: 'Retail, Food, Bakery, Grocery',
  },
  {
    key: 'booking_appointments',
    label: 'Appointment Booking',
    description: 'Allow customers to select date and time slots for appointments.',
    iconName: 'CalendarCheck',
    recommendedFor: 'Salons, Clinics, Consultants, Tutors',
  },
  {
    key: 'stay_booking',
    label: 'Hotel & Stay Booking',
    description: 'Check-in and check-out date picker with guest count calculation.',
    iconName: 'CalendarRange',
    recommendedFor: 'Hotels, Homestays, Villa Rentals',
  },
  {
    key: 'rental_booking',
    label: 'Vehicle Rental Booking',
    description: 'Start date and end date booking with vehicle count selection.',
    iconName: 'Key',
    recommendedFor: 'Self-drive Cars, Bike Rentals',
  },
  {
    key: 'inquiries',
    label: 'Direct WhatsApp Inquiry',
    description: 'One-tap WhatsApp inquiry button on every catalog item.',
    iconName: 'MessageCircle',
    recommendedFor: 'All Businesses',
  },
  {
    key: 'reviews',
    label: 'Customer Ratings & Reviews',
    description: 'Collect verified reviews and display star ratings on your storefront.',
    iconName: 'Star',
    recommendedFor: 'All Businesses',
  },
  {
    key: 'offers',
    label: 'Promotions & Coupons',
    description: 'Create discount codes and promotional banners.',
    iconName: 'Tag',
    recommendedFor: 'Retail, Food, Salons, Stays',
  },
  {
    key: 'digital_card',
    label: 'Digital Card & QR Code',
    description: 'Sharable digital visiting card and printable QR code for desk/counter.',
    iconName: 'QrCode',
    recommendedFor: 'All Businesses',
  },
  {
    key: 'inventory_tracking',
    label: 'Stock & Inventory Alerts',
    description: 'Track stock quantities and get low-stock warning indicators.',
    iconName: 'Boxes',
    recommendedFor: 'Retail, Grocery, Electronics',
  },
];
